Repository overleaf/document-updater, pull requests merged in 2020-03, with the labels that each got.

#122 use empty object for ranges if it doesn't exist
  app/coffee/DocumentManager.coffee
Labels: Team-Aqua

#123 Add ignore_flush_errors option to the doc delete endpoint
  app.coffee
  app/coffee/DocumentManager.coffee
  app/coffee/HttpController.coffee
  app/coffee/ProjectManager.coffee
  test/unit/coffee/DocumentManager/DocumentManagerTests.coffee
  test/unit/coffee/HttpController/HttpControllerTests.coffee
  test/unit/coffee/ProjectManager/flushAndDeleteProjectTests.coffee
Labels: Team-Aqua

#121 clean up package.json
  package-lock.json
  package.json
Labels: Team Ops

#126 [misc] bump logger-sharelatex to 1.9.1
  package-lock.json
  package.json
Labels: Team-Ops

#130 [misc] track redis pub/sub payload sizes on publish
  app/coffee/RealTimeRedisManager.coffee
  test/unit/coffee/RealTimeRedisManager/RealTimeRedisManagerTests.coffee
Labels: Team-Ops
