Repository overleaf/document-updater, pull requests merged in 2021-04, with the labels that each got.

#166 Update logger-sharelatex to 2.2.0
  package-lock.json
  package.json
Labels: Team-Magma

#169 [perf] use MGET for fetching multiple keys in one operation
  app/js/RedisManager.js
  test/unit/js/RedisManager/RedisManagerTests.js
Labels: Team-Magma

#163 [perf] cut redis load using mget/mset only
  app/js/RedisManager.js
  benchmarks/multi_vs_mget_mset.rb
  test/unit/js/RedisManager/RedisManagerTests.js
Labels: Team-Ops

#173 remove the limit of 300 http sockets
  config/settings.defaults.js
Labels: Team-Magma, bug

#172 upgrade ioredis via @overleaf/redis-wrapper
  package-lock.json
  package.json
Labels: Team-Magma, dependencies
